### ISSUE TITLE
编译后的文件报错

### ISSUE THREAD

**Issue by JaneCCP** [Yiyiyimu/QQ-History-Backup#22]
![2021-08-04-20-47-58](https://user-images.githubusercontent.com/62127496/128183299-e6db7b67-0832-40d6-ada2-7c3a8e80a08c.png)

**Comment by Yiyiyimu** [comment]
直接用可执行文件就好，https://github.com/Yiyiyimu/QQ-History-Backup/releases/download/v2.2.2/QQ_History_Backup_v2.2.2.zip

如果需要自己编译，需要按依赖项

**Comment by JaneCCP** [comment]
大佬能加个wx🐴

**Comment by Yiyiyimu** [comment]
有什么问题在这里问就好
