### ISSUE TITLE
每次启动都重新生成文件

### ISSUE THREAD

**Issue by cuihua0** [Yiyiyimu/QQ-History-Backup#27]
我发现每次打开程序就需要在temp下生成程序用的文件，关闭程序就会清理。
能不能改进一下，把释放的文件储存到内存，内存不容易坏，硬盘写多了容易坏。比较心疼硬盘。
或者说生成一次不要删除，下次接着用？
如果把文件储存到程序目录下面不删除也是可以的。

**Comment by Yiyiyimu** [comment]
啊这点硬盘读写不算什么的，相信你的硬盘hh

**Comment by cuihua0** [comment]
那好吧，我明白了。
