### ISSUE TITLE
想问一个模拟器获取数据库的思路......

### ISSUE THREAD

**Issue by lb-chc** [Yiyiyimu/QQ-History-Backup#28]
我在genymotion试过，但无法通过“两台设备应处于同一WIFI网络”的部分，因为系统根本就不是连接WiFi而是类似模拟有线网实现上网的......

另外扫码也有困难，有通过插件+OBS实现前置摄像头内容模拟的，但没有成功.......

**Comment by Yiyiyimu** [comment]
closed due to unrelated to this repo. please reopen it if I misunderstood.
